services:
  finance:
    build: .
    user: "1000:1000"
    environment:
      - JUPYTER_ENABLE_LAB=true
      - TZ="Asia/Tokyo"
    ports:
      - "8888:8888"
    volumes:
      - ..:/home/jovyan/work
